// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sending_2_Rename_Material_To_SamplingLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sending_2_Rename_Material_To_SamplingLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201409281610249_Sending_2_Rename_Material_To_SamplingLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
