// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Sending_Add_ForeignKeyToPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sending_Add_ForeignKeyToPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "201404142153397_Sending_Add_ForeignKeyToPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
