// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Sending_3_Add_Material_And_Make_SamplingDate_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sending_3_Add_Material_And_Make_SamplingDate_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "201409281805458_Sending_3_Add_Material_And_Make_SamplingDate_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
