// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Isolate_6_AddBestMatchForApiNHAnd16SrRNA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Isolate_6_AddBestMatchForApiNHAnd16SrRNA));
        
        string IMigrationMetadata.Id
        {
            get { return "201406102134059_Isolate_6_AddBestMatchForApiNHAnd16SrRNA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
