// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Isolate_8_BestMatchForMaldiAndMovedEvaluationAndReportDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Isolate_8_BestMatchForMaldiAndMovedEvaluationAndReportDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201408312132390_Isolate_8_BestMatchForMaldiAndMovedEvaluationAndReportDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
