// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Isolate_4_Add_StemNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Isolate_4_Add_StemNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201405051839287_Isolate_4_Add_StemNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
