// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeningoPatient_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeningoPatient_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803182109307_MeningoPatient_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
