// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeningoSending_2_SenderConclusion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeningoSending_2_SenderConclusion));
        
        string IMigrationMetadata.Id
        {
            get { return "201804181949382_MeningoSending_2_SenderConclusion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
