// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Meningo_Isolate_12_Add_SIAA_CNL_CRTA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meningo_Isolate_12_Add_SIAA_CNL_CRTA));
        
        string IMigrationMetadata.Id
        {
            get { return "201912022008344_Meningo_Isolate_12_Add_SIAA_CNL_CRTA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
