// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Meningo_Isolate_8_AdditionalFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Meningo_Isolate_8_AdditionalFields));

        string IMigrationMetadata.Id
        {
            get { return "201901182228325_Meningo_Isolate_8_AdditionalFields"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
