// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeningoSending_2_InvasiveAndNonInvasiveSamplingLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeningoSending_2_InvasiveAndNonInvasiveSamplingLocation));

        string IMigrationMetadata.Id
        {
            get { return "201901142109394_MeningoSending_2_InvasiveAndNonInvasiveSamplingLocation"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
