// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NeisseriaPubMlstIsolate_AddPubMlstIdAndFixReference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NeisseriaPubMlstIsolate_AddPubMlstIdAndFixReference));
        
        string IMigrationMetadata.Id
        {
            get { return "202002112117102_NeisseriaPubMlstIsolate_AddPubMlstIdAndFixReference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
