// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sending_AutoInvasive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sending_AutoInvasive));
        
        string IMigrationMetadata.Id
        {
            get { return "202305301958098_Sending_AutoInvasive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
