// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Isolate_RealTimePcr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Isolate_RealTimePcr));
        
        string IMigrationMetadata.Id
        {
            get { return "202410201042173_Isolate_RealTimePcr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
