// <auto-generated />
namespace HaemophilusWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SendingBase_DemisId_To_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SendingBase_DemisId_To_String));
        
        string IMigrationMetadata.Id
        {
            get { return "202404280859485_SendingBase_DemisId_To_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
