# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
        
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1.2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
      
    - name: Restore NuGet packages
      run: nuget restore HaemophilusWeb.sln 
        
    - name: Build solution
      run: msbuild HaemophilusWeb.sln 
      
    - name: Run unit tests
      run: VSTest.console.exe /Enablecodecoverage HaemophilusWebTests\bin\Debug\HaemophilusWebTests.dll 