# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      with:
        vs-version: "[16.5]"
        
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: echo MSBuild
      run: msbuild -version
    
    - name: REstore NuGet packages
      run: nuget restore HaemophilusWeb.sln 
        
    - name: Build solution
      run: msbuild HaemophilusWeb.sln 
      
    - name: Run unit tests
      run: VSTest.console.exe HaemophilusWebTests\bin\Debug\HaemophilusWebTests.dll
   
