# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
        
    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@d9a5dffa3f11d9c27ec42eb69515d3aaeaad9ef8 # v1.2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2
      with:
        nuget-version: 'latest'
      
    - name: Restore NuGet packages
      run: nuget restore HaemophilusWeb.sln 
        
    - name: Build solution
      run: msbuild HaemophilusWeb.sln 
      
    - name: Run unit tests
      run: VSTest.console.exe /Enablecodecoverage HaemophilusWebTests\bin\Debug\HaemophilusWebTests.dll 